Repository Tempo-Platform/tempo-ios-sdk, pull requests merged in 2023-07, with the labels that each got.

#8 SC-894 - CI/CD
  .github/release-drafter.yml
  .github/workflows/cocoapods-release.yml
  .github/workflows/release-drafter.yml
  README.md
  TempoSDK.podspec
  assets/tempo-logo.png
Labels: feature

#9 SC-894 - Pod Commands
  .github/release-drafter.yml
  .github/workflows/cocoapods-release.yml
  README.md
  TempoSDK.podspec
Labels: fix

#10 SC-894 - Workflow Environment
  .github/workflows/cocoapods-release.yml
Labels: fix

#11 SC-894 - git diff
  .github/workflows/cocoapods-release.yml
Labels: fix

#12 SC-894 - Output, Push & Permissions
  .github/workflows/cocoapods-release.yml
  .github/workflows/permissions-advisor.yml
Labels: fix

#13 SC-894 - Commit
  .github/workflows/cocoapods-release.yml
Labels: fix

#14 SC-894 - PODSPEC_PATH in Commit
  .github/workflows/cocoapods-release.yml
Labels: fix

#15 SC-894 - PAT
  .github/workflows/cocoapods-release.yml
Labels: fix

#16 SC-894 - Ubuntu
  .github/workflows/cocoapods-release.yml
Labels: fix

#17 SC-894 - Environment
  .github/workflows/cocoapods-release.yml
Labels: fix

#18 SC-894 - Token, Persist & Force
  .github/workflows/cocoapods-release.yml
Labels: fix

#19 SC-894 - Branch Name
  .github/workflows/cocoapods-release.yml
Labels: fix

#20 SC-894 - fetch-depth & ref
  .github/workflows/cocoapods-release.yml
Labels: fix

#21 SC-894 - Checkout Branch
  .github/workflows/cocoapods-release.yml
Labels: fix

#25 SC-894 - Autolabeler Branches
  .github/release-drafter.yml
  README.md
Labels: fix

#26 SC-894 - Metric Version
  .github/workflows/cocoapods-release.yml
  TempoSDK/Constants.swift
Labels: fix

#27 Standardised Quotes
  .github/workflows/cocoapods-release.yml
  TempoSDK.podspec
Labels: fix

#28 Git Commit All
  .github/workflows/cocoapods-release.yml
Labels: fix

#24 Refactor fc 901 refactor ios
  Example/Podfile.lock
  Example/TempoSDKTester/ViewController.swift
  TempoSDK.podspec
  TempoSDK/Constants.swift
  TempoSDK/TempoAdView.swift
  TempoSDK/TempoTesting.swift
  TempoSDK/TempoUtils.swift
Labels: refactor

#29 Changes for merge check
  Example/Podfile.lock
  TempoSDK.podspec
  TempoSDK/Constants.swift
Labels: refactor

#30 Job Dependency Issue
  .github/workflows/cocoapods-release.yml
Labels: fix
